use BDClinica;

#PAISES
INSERT INTO Nacionalidad (Descripcion) VALUES('Afganistán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Albania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Alemania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Andorra');
INSERT INTO Nacionalidad (Descripcion) VALUES('Angola');
INSERT INTO Nacionalidad (Descripcion) VALUES('Anguilla');
INSERT INTO Nacionalidad (Descripcion) VALUES('Antártida');
INSERT INTO Nacionalidad (Descripcion) VALUES('Antigua y Barbuda');
INSERT INTO Nacionalidad (Descripcion) VALUES('Antillas Holandesas');
INSERT INTO Nacionalidad (Descripcion) VALUES('Arabia Saudí');
INSERT INTO Nacionalidad (Descripcion) VALUES('Argelia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Argentina');
INSERT INTO Nacionalidad (Descripcion) VALUES('Armenia');
INSERT INTO Nacionalidad (Descripcion) VALUES('ARY Macedonia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Aruba');
INSERT INTO Nacionalidad (Descripcion) VALUES('Australia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Austria');
INSERT INTO Nacionalidad (Descripcion) VALUES('Azerbaiyán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bahamas');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bahréin');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bangladesh');
INSERT INTO Nacionalidad (Descripcion) VALUES('Barbados');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bielorrusia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bélgica');
INSERT INTO Nacionalidad (Descripcion) VALUES('Belice');
INSERT INTO Nacionalidad (Descripcion) VALUES('Benin');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bermudas');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bhután');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bolivia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bosnia y Herzegovina');
INSERT INTO Nacionalidad (Descripcion) VALUES('Botsuana');
INSERT INTO Nacionalidad (Descripcion) VALUES('Brasil');
INSERT INTO Nacionalidad (Descripcion) VALUES('Brunéi');
INSERT INTO Nacionalidad (Descripcion) VALUES('Bulgaria');
INSERT INTO Nacionalidad (Descripcion) VALUES('Burkina Faso');
INSERT INTO Nacionalidad (Descripcion) VALUES('Burundi');
INSERT INTO Nacionalidad (Descripcion) VALUES('Cabo Verde');
INSERT INTO Nacionalidad (Descripcion) VALUES('Camboya');
INSERT INTO Nacionalidad (Descripcion) VALUES('Camerún');
INSERT INTO Nacionalidad (Descripcion) VALUES('Canadá');
INSERT INTO Nacionalidad (Descripcion) VALUES('Chad');
INSERT INTO Nacionalidad (Descripcion) VALUES('Chile');
INSERT INTO Nacionalidad (Descripcion) VALUES('China');
INSERT INTO Nacionalidad (Descripcion) VALUES('Chipre');
INSERT INTO Nacionalidad (Descripcion) VALUES('Ciudad del Vaticano');
INSERT INTO Nacionalidad (Descripcion) VALUES('Colombia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Comoras');
INSERT INTO Nacionalidad (Descripcion) VALUES('Congo');
INSERT INTO Nacionalidad (Descripcion) VALUES('Corea del Norte');
INSERT INTO Nacionalidad (Descripcion) VALUES('Corea del Sur');
INSERT INTO Nacionalidad (Descripcion) VALUES('Costa de Marfil');
INSERT INTO Nacionalidad (Descripcion) VALUES('Costa Rica');
INSERT INTO Nacionalidad (Descripcion) VALUES('Croacia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Cuba');
INSERT INTO Nacionalidad (Descripcion) VALUES('Dinamarca');
INSERT INTO Nacionalidad (Descripcion) VALUES('Dominica');
INSERT INTO Nacionalidad (Descripcion) VALUES('Ecuador');
INSERT INTO Nacionalidad (Descripcion) VALUES('Egipto');
INSERT INTO Nacionalidad (Descripcion) VALUES('El Salvador');
INSERT INTO Nacionalidad (Descripcion) VALUES('Emiratos Árabes Unidos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Eritrea');
INSERT INTO Nacionalidad (Descripcion) VALUES('Eslovaquia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Eslovenia');
INSERT INTO Nacionalidad (Descripcion) VALUES('España');
INSERT INTO Nacionalidad (Descripcion) VALUES('Estados Unidos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Estonia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Etiopía');
INSERT INTO Nacionalidad (Descripcion) VALUES('Filipinas');
INSERT INTO Nacionalidad (Descripcion) VALUES('Finlandia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Fiyi');
INSERT INTO Nacionalidad (Descripcion) VALUES('Francia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Gabón');
INSERT INTO Nacionalidad (Descripcion) VALUES('Gambia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Georgia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Ghana');
INSERT INTO Nacionalidad (Descripcion) VALUES('Gibraltar');
INSERT INTO Nacionalidad (Descripcion) VALUES('Granada');
INSERT INTO Nacionalidad (Descripcion) VALUES('Grecia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Groenlandia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guadalupe');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guam');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guatemala');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guayana Francesa');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guinea');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guinea Ecuatorial');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guinea-Bissau');
INSERT INTO Nacionalidad (Descripcion) VALUES('Guyana');
INSERT INTO Nacionalidad (Descripcion) VALUES('Haití');
INSERT INTO Nacionalidad (Descripcion) VALUES('Honduras');
INSERT INTO Nacionalidad (Descripcion) VALUES('Hong Kong');
INSERT INTO Nacionalidad (Descripcion) VALUES('Hungría');
INSERT INTO Nacionalidad (Descripcion) VALUES('India');
INSERT INTO Nacionalidad (Descripcion) VALUES('Indonesia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Irán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Iraq');
INSERT INTO Nacionalidad (Descripcion) VALUES('Irlanda');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islandia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Isla Bouvet');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Caimán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Cocos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Cook');
INSERT INTO Nacionalidad (Descripcion) VALUES('Isla de Navidad');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Vírgenes Británicas');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Vírgenes de los Estados Unidos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Gland');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Feroe');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Turcas y Caicos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Heard y McDonald');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Marianas del Norte');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Marshall');
INSERT INTO Nacionalidad (Descripcion) VALUES('Isla Norfolk');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Pitcairn');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas Salomón');
INSERT INTO Nacionalidad (Descripcion) VALUES('Islas ultramarinas de Estados Unidos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Israel');
INSERT INTO Nacionalidad (Descripcion) VALUES('Italia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Jamaica');
INSERT INTO Nacionalidad (Descripcion) VALUES('Japón');
INSERT INTO Nacionalidad (Descripcion) VALUES('Jordania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Kazajstán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Kenia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Kirguistán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Kiribati');
INSERT INTO Nacionalidad (Descripcion) VALUES('Kuwait');
INSERT INTO Nacionalidad (Descripcion) VALUES('Laos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Lesotho');
INSERT INTO Nacionalidad (Descripcion) VALUES('Letonia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Líbano');
INSERT INTO Nacionalidad (Descripcion) VALUES('Liberia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Libia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Liechtenstein');
INSERT INTO Nacionalidad (Descripcion) VALUES('Lituania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Luxemburgo');
INSERT INTO Nacionalidad (Descripcion) VALUES('Macao');
INSERT INTO Nacionalidad (Descripcion) VALUES('Madagascar');
INSERT INTO Nacionalidad (Descripcion) VALUES('Malasia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Malawi');
INSERT INTO Nacionalidad (Descripcion) VALUES('Maldivas');
INSERT INTO Nacionalidad (Descripcion) VALUES('Malí');
INSERT INTO Nacionalidad (Descripcion) VALUES('Malta');
INSERT INTO Nacionalidad (Descripcion) VALUES('Marruecos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Martinica');
INSERT INTO Nacionalidad (Descripcion) VALUES('Mauricio');
INSERT INTO Nacionalidad (Descripcion) VALUES('Mauritania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Mayotte');
INSERT INTO Nacionalidad (Descripcion) VALUES('México');
INSERT INTO Nacionalidad (Descripcion) VALUES('Micronesia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Moldavia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Mónaco');
INSERT INTO Nacionalidad (Descripcion) VALUES('Mongolia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Montserrat');
INSERT INTO Nacionalidad (Descripcion) VALUES('Mozambique');
INSERT INTO Nacionalidad (Descripcion) VALUES('Myanmar');
INSERT INTO Nacionalidad (Descripcion) VALUES('Namibia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Nauru');
INSERT INTO Nacionalidad (Descripcion) VALUES('Nepal');
INSERT INTO Nacionalidad (Descripcion) VALUES('Nicaragua');
INSERT INTO Nacionalidad (Descripcion) VALUES('Níger');
INSERT INTO Nacionalidad (Descripcion) VALUES('Nigeria');
INSERT INTO Nacionalidad (Descripcion) VALUES('Niue');
INSERT INTO Nacionalidad (Descripcion) VALUES('Noruega');
INSERT INTO Nacionalidad (Descripcion) VALUES('Nueva Caledonia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Nueva Zelanda');
INSERT INTO Nacionalidad (Descripcion) VALUES('Omán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Países Bajos');
INSERT INTO Nacionalidad (Descripcion) VALUES('Pakistán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Palau');
INSERT INTO Nacionalidad (Descripcion) VALUES('Palestina');
INSERT INTO Nacionalidad (Descripcion) VALUES('Panamá');
INSERT INTO Nacionalidad (Descripcion) VALUES('Papúa Nueva Guinea');
INSERT INTO Nacionalidad (Descripcion) VALUES('Paraguay');
INSERT INTO Nacionalidad (Descripcion) VALUES('Perú');
INSERT INTO Nacionalidad (Descripcion) VALUES('Polinesia Francesa');
INSERT INTO Nacionalidad (Descripcion) VALUES('Polonia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Portugal');
INSERT INTO Nacionalidad (Descripcion) VALUES('Puerto Rico');
INSERT INTO Nacionalidad (Descripcion) VALUES('Qatar');
INSERT INTO Nacionalidad (Descripcion) VALUES('Reino Unido');
INSERT INTO Nacionalidad (Descripcion) VALUES('República Centroafricana');
INSERT INTO Nacionalidad (Descripcion) VALUES('República Dominicana');
INSERT INTO Nacionalidad (Descripcion) VALUES('República Democrática del Congo');
INSERT INTO Nacionalidad (Descripcion) VALUES('República Checa');
INSERT INTO Nacionalidad (Descripcion) VALUES('Reunión');
INSERT INTO Nacionalidad (Descripcion) VALUES('Ruanda');
INSERT INTO Nacionalidad (Descripcion) VALUES('Rumania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Rusia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Sahara Occidental');
INSERT INTO Nacionalidad (Descripcion) VALUES('Samoa');
INSERT INTO Nacionalidad (Descripcion) VALUES('Samoa Americana');
INSERT INTO Nacionalidad (Descripcion) VALUES('San Cristóbal y Nevis');
INSERT INTO Nacionalidad (Descripcion) VALUES('San Marino');
INSERT INTO Nacionalidad (Descripcion) VALUES('San Pedro y Miquelón');
INSERT INTO Nacionalidad (Descripcion) VALUES('San Vicente y las Granadinas');
INSERT INTO Nacionalidad (Descripcion) VALUES('Santa Helena');
INSERT INTO Nacionalidad (Descripcion) VALUES('Santa Lucía');
INSERT INTO Nacionalidad (Descripcion) VALUES('Santo Tomé y Príncipe');
INSERT INTO Nacionalidad (Descripcion) VALUES('Senegal');
INSERT INTO Nacionalidad (Descripcion) VALUES('Serbia y Montenegro');
INSERT INTO Nacionalidad (Descripcion) VALUES('Seychelles');
INSERT INTO Nacionalidad (Descripcion) VALUES('Sierra Leona');
INSERT INTO Nacionalidad (Descripcion) VALUES('Singapur');
INSERT INTO Nacionalidad (Descripcion) VALUES('Siria');
INSERT INTO Nacionalidad (Descripcion) VALUES('Somalia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Sri Lanka');
INSERT INTO Nacionalidad (Descripcion) VALUES('Suazilandia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Sudáfrica');
INSERT INTO Nacionalidad (Descripcion) VALUES('Sudán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Suecia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Suiza');
INSERT INTO Nacionalidad (Descripcion) VALUES('Surinam');
INSERT INTO Nacionalidad (Descripcion) VALUES('Svalbard y Jan Mayen');
INSERT INTO Nacionalidad (Descripcion) VALUES('Tailandia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Taiwán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Tanzania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Tayikistán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Territorio Británico del Océano Índico');
INSERT INTO Nacionalidad (Descripcion) VALUES('Territorios Australes Franceses');
INSERT INTO Nacionalidad (Descripcion) VALUES('Timor Oriental');
INSERT INTO Nacionalidad (Descripcion) VALUES('Togo');
INSERT INTO Nacionalidad (Descripcion) VALUES('Tokelau');
INSERT INTO Nacionalidad (Descripcion) VALUES('Tonga');
INSERT INTO Nacionalidad (Descripcion) VALUES('Trinidad y Tobago');
INSERT INTO Nacionalidad (Descripcion) VALUES('Túnez');
INSERT INTO Nacionalidad (Descripcion) VALUES('Turkmenistán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Turquía');
INSERT INTO Nacionalidad (Descripcion) VALUES('Tuvalu');
INSERT INTO Nacionalidad (Descripcion) VALUES('Ucrania');
INSERT INTO Nacionalidad (Descripcion) VALUES('Uganda');
INSERT INTO Nacionalidad (Descripcion) VALUES('Uruguay');
INSERT INTO Nacionalidad (Descripcion) VALUES('Uzbekistán');
INSERT INTO Nacionalidad (Descripcion) VALUES('Vanuatu');
INSERT INTO Nacionalidad (Descripcion) VALUES('Venezuela');
INSERT INTO Nacionalidad (Descripcion) VALUES( 'Vietnam');
INSERT INTO Nacionalidad (Descripcion) VALUES('Wallis y Futuna');
INSERT INTO Nacionalidad (Descripcion) VALUES('Yemen');
INSERT INTO Nacionalidad (Descripcion) VALUES('Yibuti');
INSERT INTO Nacionalidad (Descripcion) VALUES('Zambia');
INSERT INTO Nacionalidad (Descripcion) VALUES('Zimbabue');

#ESTADOS
INSERT INTO Estados (Descripcion) VALUES('LIBRE');
INSERT INTO Estados (Descripcion) VALUES('OCUPADO');
INSERT INTO Estados (Descripcion) VALUES('AUSENTE');
INSERT INTO Estados (Descripcion) VALUES('PRESENTE');

